#!/bin/bash
# ***************************************************************************
# 文件名称：upload_ocdp_hdfs.sh
# 功能描述：上传备份文件到大集群hdfs
# 输 入 表：
# 输 出 表：
# 创 建 者：hyn
# 创建日期：20210209
# 修改日志：
# 修改日期：
# ***************************************************************************
# 程序调用格式：sh upload_ocdp_hdfs.sh
# ***************************************************************************

#判断namenode存活主机ip：
hadoop fs -ls -d hdfs://172.19.168.100:8020/ &>/dev/null
if [ $? -eq 0 ]
then
    echo "172.19.168.100 is active"
    DATA_FROM='172.19.168.100'
else
    echo "172.19.168.4 is active"
    DATA_FROM='172.19.168.4'
fi

hadoop fs -put /data02/zyzx/scriptbak_tar/* hdfs://$DATA_FROM:8020/hadoop/interface/beifen
